### PR TITLE
feat(schedule): Add talk takeaways

### PR DESCRIPTION
**Pull request by GentileFulvio**
Added all takeaways to the json file and added an `ol` to display them in the `schedule-item-detail.component.html` 
image

### CODE REVIEW

**Review by samvloeberghs — APPROVED** [review]

**Comment by samvloeberghs** [comment]
Thanks alot!!!!

**Comment by SamVerschueren** [comment]
Thanks for doing this @GentileFulvio! Just wondering, should we put the takeaways right under the description and the speakers at the end? What do you guys think?

**Comment by samvloeberghs** [comment]
as you propose

**Comment by GentileFulvio** [comment]
You're welcome!

**Comment by GentileFulvio** [comment]
Wasn't entirely sure about that part indeed... I didt want to push the speakers down to much. On the other hand, the people probably would rather see the takeaways first...

**Pull request merged**
